In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [54]:
data = pd.read_csv("C:/Users/thiru/Downloads/Titanic Data.csv")

In [55]:
data

Sl No Name  Gender   Cabin  Age Fare Type Survived
0      1    A    Male  Upper    24  Business      Yes
1      2    B  Female   Lower   30   Premium      Yes
2      3    C    Male  Middle   35   Economy       No
3      4    D    Male  Upper    43  Business      Yes
4      5    E    Male   Lower   27   Premium       No
5      6    F  Female  Middle   37   Economy       No
6      7    G  Female  Upper    53  Business       No
7      8    H  Female   Lower   21   Premium      Yes
8      9    I    Male  Middle   60   Economy      Yes
9     10    J    Male   Lower   34   Economy      Yes

In [56]:
X = data.iloc[:,1:6].values
y = data.iloc[:,-1].values

In [57]:
X

array([['A', 'Male', 'Upper ', 24, 'Business'],
       ['B', 'Female', 'Lower', 30, 'Premium'],
       ['C', 'Male', 'Middle', 35, 'Economy'],
       ['D', 'Male', 'Upper ', 43, 'Business'],
       ['E', 'Male', 'Lower', 27, 'Premium'],
       ['F', 'Female', 'Middle', 37, 'Economy'],
       ['G', 'Female', 'Upper ', 53, 'Business'],
       ['H', 'Female', 'Lower', 21, 'Premium'],
       ['I', 'Male', 'Middle', 60, 'Economy'],
       ['J', 'Male', 'Lower', 34, 'Economy']], dtype=object)

In [58]:
y

array(['Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes'],
      dtype=object)

In [47]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder


In [59]:
le = LabelEncoder()
y = le.fit_transform(y)

In [60]:
y

array([1, 1, 0, 1, 0, 0, 0, 1, 1, 1])

In [37]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder


In [38]:
data['Genders'] = le.fit_transform(data['Gender'])


In [61]:
data['Genders'] = le.fit_transform(data['Gender'])


In [39]:
data_encoded = pd.DataFrame(ohe.fit_transform(data[['Cabin', 'Fare Type','Survived']]).toarray(), 
                          columns=data["Upper","Lower","Middle","Business","Premium","Economy","Yes","No"])


KeyError: ('Upper', 'Lower', 'Middle', 'Business', 'Premium', 'Economy', 'Yes', 'No')

In [40]:
data_encoded = pd.DataFrame(ohe.fit_transform(data[['Cabin', 'Fare Type', 'Survived']]).toarray(),
                            columns=['Upper', 'Lower', 'Middle', 'Business', 'Premium', 'Economy', 'Yes', 'No'])


In [62]:
X_encoded = pd.DataFrame(ohe.fit_transform(X[['Name','Cabin', 'Fare Type']]).toarray(),
                            columns=['A','B','C','D','E','F','G','H','I','J','Upper', 'Lower', 'Middle', 'Business', 'Premium', 'Economy'])


C:\Users\thiru\AppData\Local\Temp/ipykernel_51084/3870421873.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  X_encoded = pd.DataFrame(ohe.fit_transform(X[['Name','Cabin', 'Fare Type']]).toarray(),


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [41]:
data = pd.concat([data, data_encoded], axis=1)


In [42]:
data.drop(['Gender','Cabin', 'Fare Type', 'Survived'], axis=1, inplace=True)


In [43]:
data

Sl No Name  Age  Genders  Upper  Lower  Middle  Business  Premium  Economy  \
0      1    A   24        1    0.0    0.0     1.0       1.0      0.0      0.0   
1      2    B   30        0    1.0    0.0     0.0       0.0      0.0      1.0   
2      3    C   35        1    0.0    1.0     0.0       0.0      1.0      0.0   
3      4    D   43        1    0.0    0.0     1.0       1.0      0.0      0.0   
4      5    E   27        1    1.0    0.0     0.0       0.0      0.0      1.0   
5      6    F   37        0    0.0    1.0     0.0       0.0      1.0      0.0   
6      7    G   53        0    0.0    0.0     1.0       1.0      0.0      0.0   
7      8    H   21        0    1.0    0.0     0.0       0.0      0.0      1.0   
8      9    I   60        1    0.0    1.0     0.0       0.0      1.0      0.0   
9     10    J   34        1    1.0    0.0     0.0       0.0      1.0      0.0   

   Yes   No  
0  0.0  1.0  
1  0.0  1.0  
2  1.0  0.0  
3  0.0  1.0  
4  1.0  0.0  
5  1.0  0.0  
6  1.0  0.0  
7  0.0  1.0  
8  0.0  1.0  
9  0.0  1.0

In [ ]:
['size_large', 'size_medium', 'size_small', 'shape_circle', 'shape_square'])


# Prerpocessing the data

In [13]:
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [21]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder


In [23]:
le = LabelEncoder()
X[:, 5] = le.fit_transform(X[:, 5])

In [24]:
ohe = OneHotEncoder(handle_unknown = 'ignore')
ohe.fit(X)

OneHotEncoder(handle_unknown='ignore')

In [26]:
X

array([[1, 'A', 'Male', 'Upper ', 24, 0],
       [2, 'B', 'Female', 'Lower', 30, 2],
       [3, 'C', 'Male', 'Middle', 35, 1],
       [4, 'D', 'Male', 'Upper ', 43, 0],
       [5, 'E', 'Male', 'Lower', 27, 2],
       [6, 'F', 'Female', 'Middle', 37, 1],
       [7, 'G', 'Female', 'Upper ', 53, 0],
       [8, 'H', 'Female', 'Lower', 21, 2],
       [9, 'I', 'Male', 'Middle', 60, 1],
       [10, 'J', 'Male', 'Lower', 34, 1]], dtype=object)

# Splitting to the train and testing

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [28]:
X_train

array([[5, 'E', 'Male', 'Lower', 27, 2],
       [10, 'J', 'Male', 'Lower', 34, 1],
       [2, 'B', 'Female', 'Lower', 30, 2],
       [7, 'G', 'Female', 'Upper ', 53, 0],
       [8, 'H', 'Female', 'Lower', 21, 2],
       [4, 'D', 'Male', 'Upper ', 43, 0],
       [1, 'A', 'Male', 'Upper ', 24, 0],
       [6, 'F', 'Female', 'Middle', 37, 1]], dtype=object)

In [29]:
X_test

array([[3, 'C', 'Male', 'Middle', 35, 1],
       [9, 'I', 'Male', 'Middle', 60, 1]], dtype=object)

In [30]:
y_train


array(['No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No'], dtype=object)

In [31]:
y_test

array(['No', 'Yes'], dtype=object)

In [33]:
from sklearn.linear_model import LogisticRegression
regressor = LogisticRegression()
regressor.fit(X_train,y_train)

ValueError: could not convert string to float: 'E'

In [ ]:
Upper	24	Business	Yes
1	2	B	Female	Lower	30	Premium	Yes
2	3	C	Male	Middle	35	Economy	No
3	4	D	Male	Upper	43	Business	Yes
4	5	E	Male	Lower	27	Premium	No
5	6	F	Female	Middle	37	Economy	No
6	7	G	Female	Upper	53	Business	No
7	8	H	Female	Lower	21	Premium	Yes
8	9	I	Male	Middle	60	Economy	Yes
9	10	J	Male	Lower	34	Economy	Yes

In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [67]:
data = pd.read_csv("C:/Users/thiru/Downloads/Titanic Data.csv")

In [68]:
data

Sl No Name  Gender   Cabin  Age Fare Type Survived
0      1    A    Male  Upper    24  Business      Yes
1      2    B  Female   Lower   30   Premium      Yes
2      3    C    Male  Middle   35   Economy       No
3      4    D    Male  Upper    43  Business      Yes
4      5    E    Male   Lower   27   Premium       No
5      6    F  Female  Middle   37   Economy       No
6      7    G  Female  Upper    53  Business       No
7      8    H  Female   Lower   21   Premium      Yes
8      9    I    Male  Middle   60   Economy      Yes
9     10    J    Male   Lower   34   Economy      Yes

In [71]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder


In [72]:
le = LabelEncoder()
data['Genders'] = le.fit_transform(data['Gender'])


In [73]:
data_encoded = pd.DataFrame(ohe.fit_transform(data[['Cabin', 'Fare Type']]).toarray(),
                            columns=['Upper', 'Lower', 'Middle', 'Business', 'Premium', 'Economy'])


In [74]:
data = pd.concat([data, data_encoded], axis=1)


In [75]:
data.drop(['Gender','Cabin', 'Fare Type'], axis=1, inplace=True)


In [76]:
data

Sl No Name  Age Survived  Genders  Upper  Lower  Middle  Business  Premium  \
0      1    A   24      Yes        1    0.0    0.0     1.0       1.0      0.0   
1      2    B   30      Yes        0    1.0    0.0     0.0       0.0      0.0   
2      3    C   35       No        1    0.0    1.0     0.0       0.0      1.0   
3      4    D   43      Yes        1    0.0    0.0     1.0       1.0      0.0   
4      5    E   27       No        1    1.0    0.0     0.0       0.0      0.0   
5      6    F   37       No        0    0.0    1.0     0.0       0.0      1.0   
6      7    G   53       No        0    0.0    0.0     1.0       1.0      0.0   
7      8    H   21      Yes        0    1.0    0.0     0.0       0.0      0.0   
8      9    I   60      Yes        1    0.0    1.0     0.0       0.0      1.0   
9     10    J   34      Yes        1    1.0    0.0     0.0       0.0      1.0   

   Economy  
0      0.0  
1      1.0  
2      0.0  
3      0.0  
4      1.0  
5      0.0  
6      0.0  
7      1.0  
8      0.0  
9      0.0

In [77]:
data['survived'] = data["Survived"]

In [79]:
data.drop(['Survived'],axis = 1,inplace = True)

In [80]:
data

Sl No Name  Age  Genders  Upper  Lower  Middle  Business  Premium  Economy  \
0      1    A   24        1    0.0    0.0     1.0       1.0      0.0      0.0   
1      2    B   30        0    1.0    0.0     0.0       0.0      0.0      1.0   
2      3    C   35        1    0.0    1.0     0.0       0.0      1.0      0.0   
3      4    D   43        1    0.0    0.0     1.0       1.0      0.0      0.0   
4      5    E   27        1    1.0    0.0     0.0       0.0      0.0      1.0   
5      6    F   37        0    0.0    1.0     0.0       0.0      1.0      0.0   
6      7    G   53        0    0.0    0.0     1.0       1.0      0.0      0.0   
7      8    H   21        0    1.0    0.0     0.0       0.0      0.0      1.0   
8      9    I   60        1    0.0    1.0     0.0       0.0      1.0      0.0   
9     10    J   34        1    1.0    0.0     0.0       0.0      1.0      0.0   

  survived  
0      Yes  
1      Yes  
2       No  
3      Yes  
4       No  
5       No  
6       No  
7      Yes  
8      Yes  
9      Yes

In [81]:
X = data.iloc[:,2:10].values
y = data.iloc[:,-1].values

In [82]:
X

array([[24.,  1.,  0.,  0.,  1.,  1.,  0.,  0.],
       [30.,  0.,  1.,  0.,  0.,  0.,  0.,  1.],
       [35.,  1.,  0.,  1.,  0.,  0.,  1.,  0.],
       [43.,  1.,  0.,  0.,  1.,  1.,  0.,  0.],
       [27.,  1.,  1.,  0.,  0.,  0.,  0.,  1.],
       [37.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [53.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [21.,  0.,  1.,  0.,  0.,  0.,  0.,  1.],
       [60.,  1.,  0.,  1.,  0.,  0.,  1.,  0.],
       [34.,  1.,  1.,  0.,  0.,  0.,  1.,  0.]])

In [83]:
y

array(['Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes'],
      dtype=object)

In [84]:
y = le.fit_transform(y)

In [85]:
y

array([1, 1, 0, 1, 0, 0, 0, 1, 1, 1])

# train and test the model:

In [87]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

# Fitting the train and testing:

In [88]:
from sklearn.linear_model import LogisticRegression
regressor = LogisticRegression()
regressor.fit(X_train,y_train)

LogisticRegression()

In [90]:
y_pred = regressor.predict(X_test)

In [91]:
print(y_pred)

[0 0]


In [92]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[1 0]
 [1 0]]


In [93]:
accuracy_score(y_test,y_pred)

0.5

# Decision tree:

In [94]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy',random_state = 0)
classifier.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

# prediction

In [95]:
y_pred = classifier.predict(X_test)

In [96]:
y_pred

array([0, 0])

In [97]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[1 0]
 [1 0]]


In [98]:
accuracy_score(y_test,y_pred)

0.5